Repository apache/stormcrawler, pull requests merged in 2021-11, with the labels that each got.

#923 Support HEAD method in okhttp protocol
  core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
Labels: enhancement

#920 Upgrade to Tika 2.1.0
  archetype/src/main/resources/archetype-resources/crawler-conf.yaml
  core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
  external/elasticsearch/archetype/src/main/resources/archetype-resources/crawler-conf.yaml
  external/tika/README.md
  external/tika/pom.xml
  external/tika/src/main/java/com/digitalpebble/stormcrawler/tika/ParserBolt.java
  external/tika/src/main/java/com/digitalpebble/stormcrawler/tika/RedirectionBolt.java
  external/tika/src/main/resources/tika-config.xml
  pom.xml
Labels: enhancement, parser

#927 Remove static keyword on JSoupFilters field
  core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupFilters.java
  core/src/main/java/com/digitalpebble/stormcrawler/parse/ParseFilters.java
Labels: bug, parser

#932 Changed ProtocolFactory to be a singleton but can hold more than one …
  core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
  core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java
  core/src/main/java/com/digitalpebble/stormcrawler/filtering/robots/RobotsFilter.java
  core/src/main/java/com/digitalpebble/stormcrawler/protocol/ProtocolFactory.java
  core/src/main/resources/crawler-default.yaml
Labels: enhancement

#918 OkHttp protocol: make connection pool configurable
  core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
  core/src/main/resources/crawler-default.yaml
Labels: enhancement, fetcher
